### ISSUE TITLE
Issue with ipv4

### ISSUE THREAD

**Issue by gregoryb** [andyjack/geoip2-haproxy-ranges#1]
I'm trying to generate country files to use them in HaProxy. I use the Maxmind Geolite2 Country database but it's seems to contains only ipv6 address (translation?). Is there a way to get the ipv4 ?

Thank you.

**Comment by andyjack** [comment]
Hi - I do see IPv4 addresses, e.g. from GeoLite2-Country.mmdb that I downloaded today:

```
$ grep --line-number '/24$' country-subnets/FR.txt | head -n5
26262:2.17.35.0/24
26263:2.17.36.0/24
26333:2.17.41.0/24
26334:2.17.42.0/24
26399:2.20.244.0/24
```

I think because of the ordering of networks that come out of the .mmdb file, the IPv4 addresses end up somewhere in the middle of the output, so they can be hard to find at a glance.
